# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-26 14:23
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vnev', models.CharField(max_length=100, verbose_name='Vonat megnevezése')),
                ('indulas', models.CharField(max_length=250, verbose_name='Indulás helye')),
                ('indulas_ido', models.DateTimeField(verbose_name='Várható indulás')),
                ('belepes', models.CharField(blank=True, max_length=250, null=True, verbose_name='Belépés helye ha tranzit')),
                ('belepes_ido', models.DateTimeField(blank=True, null=True, verbose_name='Belépés ideje ha tranzit')),
                ('erkezes', models.CharField(blank=True, max_length=250, null=True, verbose_name='Érkezés helye')),
                ('kilepes', models.CharField(blank=True, max_length=250, null=True, verbose_name='Kilépés helye ha tranzit')),
                ('rakott', models.BooleanField(verbose_name='Rakott')),
                ('rakomany_fajta', models.CharField(blank=True, max_length=150, null=True, verbose_name='Rakomány fajtája')),
                ('brutto_tonna', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bruttó tonna')),
                ('fekhossz', models.IntegerField(blank=True, null=True, verbose_name='Féktechnikai hosszúság')),
                ('megjegyzesek', models.TextField(blank=True, max_length=350, null=True, verbose_name='Megjegyzések')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='mozdony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mozdony', models.CharField(max_length=12, verbose_name='Továbbító mozdony')),
                ('mozdony_hozzarendelve', models.DateTimeField(blank=True, null=True, verbose_name='Mozdony hozzárendelve')),
                ('megjegyzesek', models.TextField(blank=True, max_length=350, null=True, verbose_name='Megjegyzések')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rail.Album', verbose_name='vonat kiválasztása')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='vpe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vpe', models.CharField(blank=True, max_length=14, null=True, verbose_name='VPE szám')),
                ('indulas_ido', models.DateTimeField(verbose_name='Tényleges indulás/határtól ha tranzit')),
                ('kilepes_igazolt', models.DateTimeField(blank=True, null=True, verbose_name='Kilépés visszaigazolt ideje ha tranzit')),
                ('kilepes_tenyleges', models.DateTimeField(blank=True, null=True, verbose_name='Tényleges kilépés ideje ha tranzit')),
                ('erekezes_ido', models.DateTimeField(blank=True, null=True, verbose_name='Tényleges érkezés ideje ha nem tranzit')),
                ('megjegyzesek', models.TextField(blank=True, max_length=350, null=True, verbose_name='Megjegyzések')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rail.Album', verbose_name='vonat kiválasztása')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
