# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rail', '0002_auto_20160702_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mozdony',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vpe',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
