# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 13:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rail', '0012_auto_20160705_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='helyzet',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Vonat jelenlegi helyzete'),
        ),
        migrations.AlterField(
            model_name='album',
            name='brutto_tonna',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bruttó tonna*'),
        ),
        migrations.AlterField(
            model_name='album',
            name='fekhossz',
            field=models.IntegerField(blank=True, default='', null=True, verbose_name='Féktechnikai hosszúság'),
        ),
        migrations.AlterField(
            model_name='album',
            name='indulas',
            field=models.CharField(max_length=250, verbose_name='Indulás helye*'),
        ),
        migrations.AlterField(
            model_name='album',
            name='indulas_ido',
            field=models.DateTimeField(verbose_name='Várható indulás*'),
        ),
        migrations.AlterField(
            model_name='album',
            name='vnev',
            field=models.CharField(max_length=100, verbose_name='Vonat megnevezése*'),
        ),
    ]
