# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rail', '0013_auto_20160705_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='fekhossz',
            field=models.IntegerField(blank=True, null=True, verbose_name='Féktechnikai hosszúság'),
        ),
        migrations.AlterField(
            model_name='album',
            name='helyzet',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Legutóbb ismert helyzete'),
        ),
    ]
